### PR TITLE
Single phase + outlier clusterer support and other additions

### PR DESCRIPTION
**Pull request by dkrleza**
All additions in this pull request are done taking in consideration backwards compatibility.
1. **Evaluation update**
The evaluation functions, _evaluate_ and _evaluate_cluster_ are extended with callback handlers, so that clusterer implementators can contribute with external measurement implementations, without need to change the _stream_ package. The original code was preserved, but reorganized, to accomodate callback methods, single phase approach and outlier clusterers.<br>
Added the _OutlierJaccard_ measure that can be applied to the outlier clusterers, to assess how accurately clusterer classified the generated outliers: an extension of the DSD class is made, so that data stream generators can now mark outliers.

2. **DSD_Gaussians extensions**
- Added outlier generation capabilities
- Besides Euclidean separation, it is possible to use Mahalanobis distance for the separation measure now
- Ability to define space limits
- Ability to define outlier generation horizon
- Ability to define maximal variance when generating covariance matrix
- Data instances storing, for the stream reproducibility purposes
- Ability to verbose data generating process
- Allows defining _virtual variance_ around outliers

3. **New classes**
**DSC_SinglePass** class that allows to define clusterers working in the phases _assignment_->_model update_ for each and every data instance from the input data stream. Evaluation functions now support such single-pass clusterers. For these clusterers, you can use either _update_ or _get_assignment_ functions, no need to use both in the same code snippet. Either you **only** update the model with _update_ call, or you retrieve classifications at the same time with _get_assignment_ call.<br>
**DSC_Outlier** class that allows to define outlier detection clusterers. This class defines additional methods:
- _clean_outliers_ - Instructing the clusterer to clear the list of outliers.
- _get_outlier_positions_ - Similar to _get_centers_ for the clustering part. The addressed clusterer returns the list of spatial outlier positions.
- _recheck_outlier_ - Needed by the _evaluation_ functions to allow backwards rechecking of the outliers. This is especially needed when _evaluate_cluster_ is used.
- _noutliers_ - Returns the number of current outliers, which can change if we proceed processing the input data stream.
- _print_ - Printout for the outlier detecting clusterers, that included outlier number as well.
- _get_assignment_ - Overriden assignment method. Outlier clusterers must return _outliers_ and _ourliers_corrid_ attributes in the predicted class vector, for using in the _evaluation_ functions.

4. **Update of the existing classes and methods**
- DSC plotting method is updated, to display and mark outliers. Such method now can use `code=c("auto", "micro", "macro", "both", "outliers", "all")`.

- Outlier stream generators (DSD) can add the _outliers_ (logical vector) attribute in the output vector (retrieved by _get_points_) to mark outliers.

- Other DSD class final implementations are slightly modified to accomodate new interface.

- DSC_TwoStage class is modified to accept single pass and outlier detecting micro-clusterers.

- _write_stream_ can now store outlier marks, which can be again read by DSD_ReadCSV.

- DSD_ReadDB can now read outlier marks from a column in a database.

- DSD_Memory and DSD_ScaleStream can now work with outlier generating DSD objects.

Example:
`d <- DSD_Gaussians(k=10,d=2,o=10,lim=c(0,50),separation_type="Mahalanobis",outlier_horizon=10000,variance_lim=2,mahalanobis_separation=6)
plot(d,n=10000)
reset_stream(d)
mic_c <- DSC_MCOD(r=4.75,w=10000)
mac_c <- DSC_Kmeans(10,weighted=T)
c <- DSC_TwoStage(mic_c,mac_c)
evaluate(c,d,n=10000,type="macro",measure=c("cRand","OutlierJaccard"))
reset_stream(d)
plot(c,d,n=10000,type="all")`

Example 2: 
`d <- DSD_Gaussians(k=10,d=2,o=10,lim=c(0,50),separation_type="Mahalanobis",outlier_horizon=10000,variance_lim=2,mahalanobis_separation=6)
plot(d,n=10000)
reset_stream(d)
mic_c <- DSC_MCOD(r=4.75,w=10000)
mac_c <- DSC_Kmeans(10,weighted=T)
c <- DSC_TwoStage(mic_c,mac_c)
evaluate_cluster(c,d,n=10000,type="macro",measure=c("cRand","OutlierJaccard"),horizon=1000)
reset_stream(d)
plot(c,d,n=10000,type="all")`

Example 3: 
`d <- DSD_Gaussians(k=10,d=2,o=10,lim=c(0,50),separation_type="Mahalanobis",outlier_horizon=10000,variance_lim=2,mahalanobis_separation=6,verbose=T)
plot(d,n=10000)
reset_stream(d)
mic_c <- DSC_MCOD(r=4.75,w=10000)
mac_c <- DSC_Kmeans(10,weighted=T)
c <- DSC_TwoStage(mic_c,mac_c)
evaluate_cluster(c,d,n=10000,type="macro",measure=c("cRand","OutlierJaccard"),horizon=1000,verbose=T)
reset_stream(d)
plot(c,d,n=10000,type="outliers")
`

### CODE REVIEW

**Comment by dkrleza** [comment]
Just a small addition for the given examples. DSC_MCOD comes from the _streamMOA_ package, so these examples can be executed only after both _stream_ and _streamMOA_ contributions are built and installed in the order: first _stream_, second _streamMOA_.

**Comment by dkrleza** [comment]
Done. It is passing the CRAN checks now. Updated the version to 1.4-0.
Updated the vignettes as well. Added my name to the DESCRIPTION file and related Rd files.

**Comment by mhahsler** [comment]
Just a quick question. The stream package itself does not have a concrete implementation of DSC_Outlier. Is that correct?

**Comment by dkrleza** [comment]
Hi,

Short answer: Yes.
I found only MCOD in MOA (_streamMOA_) that was suitable for this. Possibly there are some additional algorithms in MOA. Some of the algorithms in _stream_ are actually enclosing outliers in small clusters and this could be used for detection, however they do not have strict outlier correlation, so you never know whether some of the outliers became an inlier or not. This is a bit unfortunate, because now the _stream_ vignette looks like its missing something... examples.

The thing is, I did not want to add _stream_ -> _streamMOA_ dependency.

I plan to add one outlier detector to the _stream_ package (its written in pure C++). However, since some of my articles are still being reviewed and in making, I plan to add it when everything gets done. Maximally in month or two. I actually use _stream_ already, as it is quite nice frameworks to connect all the pieces together. It was just missing couple of features.
Screenshot 2020-10-23 at 18 52 22

**Comment by mhahsler** [comment]
I am not sure I understand the o parameter:

> stream4 <- DSD_Gaussians(k=2, o=10, d=2, separation_type="Mahalanobis",
+     mahalanobis_separation=6, lim=c(0,10), variance_lim=2)

I thought o=10 would produce more outliers, but it seems to just run for a long time. Would we want to specify outliers as a percentage of the generated data points?

**Comment by dkrleza** [comment]
It is absolutely possible to add such option. Outliers are usually sparse in the overall stream, e.g., <1% for example. That is the reason why normal indices don't work when assessing the outlier detection correctness, since the overall ratio of the affected data points is quite low.

Regarding slowness of the generation, this particular example uses quite big separation and variance, since I wanted to create nice example with nice values and pictures. Rising space in the example can help. I have also noticed that the part of the DSD_Gaussians code that generates clusters always recalculates all cluster centroids if separation is not adequate. This is something that could be improved.

**Comment by dkrleza** [comment]
Try for example
`stream4 <- DSD_Gaussians(k=2, o=10, d=2, separation_type="Mahalanobis", lim=c(0,10), variance_lim=2, outlier_virtual_variance = 0.3)`

`plot(stream4)`

**Comment by mhahsler** [comment]
That makes sense. The documentation needs to explain this, otherwise, we will get bug reports. It seems that the outliers are outlier clusters/generators?

```
stream4 <- DSD_Gaussians(k=2, o=10, d=2, separation_type="Mahalanobis", lim=c(0,10), variance_lim=2, outlier_virtual_variance = 0.3)

stream4
  Mixture of Gaussians
  Class: DSD_Gaussians, DSD_R, DSD_data.frame, DSD 
  With 2 clusters and 10 outliers in 2 dimensions 

plot(stream4)
plot(stream4)
```

The first plot includes outliers and the second and any subsequent calls of plot shows no more visible outliers.

**Comment by dkrleza** [comment]
Ok. I will update documentation, and I will try to fix the random centroid generation procedure a bit, so that it becomes quicker. Also, I will try to lower the halting conditions, so users get that "not solvable" message sooner.

About difference between noise and outliers: outliers are important and meaningful data points. We build special outlier detectors to detect them in big data streams. Detecting small statistical differences between clusters and outliers is the key feature of a good outlier detector. On the other hand, noise is just a nuissance, a set of erroneous data points that interfere with proper clustering in your algorithm.
Synthetic outlier generators are... just an adjustable approximation. The key is to have a bunch of parameters that allow you to make these statistical separations between clusters and outliers smaller and smaller, to detect the breaking point of your outlier detector, i.e., the point where the outlier detector does not correctly recognize outliers anymore.

**Comment by dkrleza** [comment]
Done.

**Comment by mhahsler** [comment]
I am running a little behind with things. It will take a little till I have time to get back to this.

**Comment by dkrleza** [comment]
I'm wrapping up another package that depends on the new _stream_, so I'm actually noticing some little details... and fixing it.

**Comment by mhahsler** [comment]
All the changes are good. The only interface improvement that I have is for:

```
DSD_Gaussians(k=2, d=2, mu, sigma, p, noise = 0, noise_range,
              separation_type=c("auto","Euclidean","Mahalanobis"), separation=0.2,
              mahalanobis_separation=4, outlier_virtual_variance=1,
              o = 0, lim = c(0.2,0.8), variance_lim = 0.01, outlier_horizon,
              outs, out_positions, verbose=FALSE)
```

It has now way too many parameters.

```
DSD_Gaussians(k=2, d=2, mu, sigma, p, noise = 0, noise_range,
              outlier = 0, outlier_parameter = NULL, verbose = FALSE)
```

And outlier_parameters can be a list with all the parameters.

Would that make sense?

**Comment by dkrleza** [comment]
Some details:
- *separation* is an old parameter that needs to stay as-is for the backward compatibility
- *separation_type*, and _mahalanobis_separation_ are not outlier-exclusive parameters.... I think these should remain top-level parameters, I will try to reduce the number of these... I will use *separation* based on the *separation_type*.
- *variance_lim* is a variance maximal limit, which is also not outlier related
- *lim* defines space bounds and is also not outlier related
- everything else can be placed as you suggested, in the *outlier_params*, to reduce the number of parameters

I suggest
```
DSD_Gaussians(k=2, d=2, mu, sigma, p, noise = 0, noise_range, separation=0.2,
              separation_type=c("auto","Euclidean","Mahalanobis"), space_limit = c(0.2,0.8), 
              variance_limit = 0.01, outliers = 0, outlier_parameters = NULL, verbose = FALSE)
```

Users don't need to use more parameters than they used previously... default values make sure of that.

Is this ok??

**Comment by mhahsler** [comment]
I got confused by the following in the man page: 

separation: Minimum Euclidean distance **between cluster centers and outliers** to reduce overlap between them (0-.8). Effective only when separation_type is either auto or Euclidean.

But after thinking about it, you probably mean: Minimum distance (Euclidean or Mahalanobis) between randomly created cluster centers to reduce overlap. If outliers are used then ...

Can separation and mahalanobis_separation be just called separation and then used dependent on how separation type is set? Or does Mahalanobis need separation and mahalanobis_separation?

The range for separation needs description. I think [0-.8] came from the idea that the data is created in a unit square...

Are the space limits observed by outliers, noise and the data?

**Comment by dkrleza** [comment]
The separation thingie makes sense. One parameter named _separation_ that is the value, and anothe parameter _separation_type_ that represents the type of the separation.
For the documentation part: I was a bit lazy and just updated already existing explanation for the _separation_ parameter. Will correct it as you suggest.

Space limits apply to everything. Default values are set for backwards compatibility.

I will make the changes tomorrow morning and commit them.

**Comment by dkrleza** [comment]
Updated.

**Comment by mhahsler** [comment]
On the way to CRAN. I will look at streamMOA next.

**Comment by dkrleza** [comment]
I see it is up already. Great. I can proceed with that dependant paper. I think streamMOA has a bit fewer updates.
After we submit the paper, I will add SH clusterer to the stream package.

**Pull request merged**
