### PR TITLE
Added BICO algorithm

### PR DESCRIPTION
**Pull request by MatthiasCarnein**
Interface to the C++ implementation of BICO as available here: http://ls2-www.cs.tu-dortmund.de/grav/de/bico

The code requires C++11 and the boosting lirbary. For this reason I added a makevars file and linked to the BH package. To keep the /src directory clean, I put all BICO code into a subfolder. I tried to keep the changes to the package minimal and as CRAN friendly as possibly. Roxygen documentation for the `DSC_BICO` function is available.

Thanks to the original authors for agreeing to publish the code.

### CODE REVIEW

**Comment by mhahsler** [comment]
I finally had time to look at the code (sorry for the delay). It looks very good. I get the following warnings from check:

```
* checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makevars
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif. See section ‘Writing portable packages’ in
the ‘Writing R Extensions’ manual.
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking compiled code ... NOTE
File ‘stream/libs/stream.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
    Object: ‘BICO.o’
  Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
    Object: ‘BICO.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor the system RNG.
```
You need to fix the Makevars file and comment out the output lines. During compilation, I get the 
following warnings:

```
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -I. -I"/home/hahsler/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/hahsler/R/x86_64-pc-linux-gnu-library/3.2/BH/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-pIzt6B/r-base-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c BICO.cpp -o BICO.o
In file included from BICO.cpp:25:0:
BICO/master.h: In member function ‘bool MASTER::readFile(char*)’:
BICO/master.h:201:46: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     std::fscanf(input, "%d", &numberOfPoints);
                                              ^
BICO/master.h:206:40: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         std::fscanf(input, "%lf", &val);
                                        ^
BICO/master.h: In member function ‘void MASTER::readInitialCenters(char*)’:
BICO/master.h:260:40: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         std::fscanf(input, "%lf", &val);
```
                          
These need to be fixed before we can send it to CRAN. 

I am still running the check on Windows (via https://win-builder.r-project.org/upload.aspx ).  

Thanks,
Michael

**Comment by MatthiasCarnein** [comment]
Thanks for the feedback. I removed the stdout/stderr output. Regarding the makevars file we have several options:

1. List all target files in the makevars to get rid of the GNU wildcards.
2. Do not change the makevars but add `SystemRequirements: GNU make` to the Description file.
3. Move all files from the subfolder into /src directly and do not use a makevars file.

I chose option 1 to have as few system dependencies as possible. However, this means that we need to maintain this list and append future files that require compilation. Option 2 would be less maintenance.

Lastly, I am not able to reproduce the compilation warnings for `fscanf` on Windows, Ubuntu or Mac but I hope assigning the return value of `fscanf` resolved the warning.

Best regards,
Matthias

**Comment by mhahsler** [comment]
Thanks. I the code is now merged into stream.

**Comment by MatthiasCarnein** [comment]
It appears that the original implementation does not deallocate a few arrays properly.
Fixing the deallocation removes the valgrind warnings for me.

Since I cannot add more commits to this Pull-Request, I will open a new one.

**Comment by mhahsler** [comment]
OK. Thanks! 
-Michael

**Comment by mhahsler** [comment]
The new version of stream is now on CRAN.

**Pull request merged**
