### PR TITLE
fix: add backports implementation for deparse1

### PR DESCRIPTION
**Pull request by m-muecke**

### CODE REVIEW

**Comment by mhahsler** [comment]
What feature needs R 4.0.0? Can we stay at 3.5.0?

**Comment by m-muecke** [comment]
Currently `deparse1()` requires 4.0.0, sure we can just copy the backports implementation over: https://github.com/r-lib/backports/blob/main/R/deparse1.R

**Comment by mhahsler** [comment]
Yes, please add this with a comment that it can be removed with R 4.0.0

**Comment by m-muecke** [comment]
> Yes, please add this with a comment that it can be removed with R 4.0.0

done

**Pull request merged**
